version: '3'
services:
  react:
    image: 435770184212.dkr.ecr.us-east-1.amazonaws.com/ecs:latest
    ports:
      - 80:3000
    task_definition:
      ecs_network_mode: awsvpc
      task_execution_role: ecsTaskExecutionRole
      task_size:
        cpu_limit: 256
        mem_limit: 512
    deploy:
      placement:
        constraints:
          - "distinctInstance"






